### PR TITLE
build: add texworks

### PR DESCRIPTION
**Pull request by wjyrich**
texworks
TeXworks is an environment for authoring TeX (LaTeX, ConTeXt, etc) documents, with a Unicode-based, TeX-aware editor, integrated PDF viewer, and a clean, simple interface accessible to casual and non-technical users.

Log: add software name--texworks

### CODE REVIEW

**Comment by lampze** [comment]
编译出错，麻烦看一下。

**Review by kamiyadm — APPROVED** [review]

**Pull request merged**
