### PR TITLE
build: add app tictactoe

### PR DESCRIPTION
**Pull request by aizhuzhudegua**
tictactoe.

Logs: add app name--tictactoe
b3549b77ee27dfa34361aba26f95a54

### CODE REVIEW

**Comment by aizhuzhudegua** [comment]
b3549b77ee27dfa34361aba26f95a54

**Comment by kamiyadm** [comment]
patch名字错了导致构建失败

**Comment by aizhuzhudegua** [comment]
> patch名字错了导致构建失败
已解决

**Comment by kamiyadm** [comment]
demo类型

**Pull request closed without merging**
